export const REQUEST_DOCUMENT_LIST_TO_DJANGO = 'REQUEST_DOCUMENT_LIST_TO_DJANGO'
export const REQUEST_DOCUMENT_TO_DJANGO = 'REQUEST_DOCUMENT_TO_DJANGO'
export const INCREMENT_DOCUMENT_VIEW_COUNT = 'INCREMENT_DOCUMENT_VIEW_COUNT'