export const REQUEST_NICKNAME_TO_DJANGO = 'REQUEST_NICKNAME_TO_DJANGO'
export const REQUEST_EMAIL_TO_DJANGO = 'REQUEST_EMAIL_TO_DJANGO'
export const REQUEST_GENDER_TO_DJANGO = 'REQUEST_GENDER_TO_DJANGO'
export const REQUEST_BIRTHYEAR_TO_DJANGO = 'REQUEST_BIRTHYEAR_TO_DJANGO'